"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";

export type GroupActionState={status:"idle"|"error";message?:string};
async function client(){const s=await createClient();const{data,error}=await s.auth.getClaims();if(error||typeof data?.claims?.sub!=="string")redirect("/login");return s;}
function failure(action:string,error:{code?:string}|null,copy:string){console.error("Group action failed",{action,code:error?.code});return{status:"error" as const,message:copy};}
export async function createGroupAction(_:GroupActionState,form:FormData):Promise<GroupActionState>{const s=await client();const{data,error}=await s.rpc("create_study_group",{p_name:String(form.get("name")??"")});if(error)return failure("create",error,error.code==="23505"?"You already have a Circle with that name.":"We couldn’t create the Circle. Check the name and try again.");redirect(`/groups/${data}`);}
export async function joinGroupAction(_:GroupActionState,form:FormData):Promise<GroupActionState>{const s=await client();const{data,error}=await s.rpc("join_study_group",{p_token:String(form.get("token")??"")});if(error)return failure("join",error,"This invite is unavailable. Ask the owner for a new link.");redirect(`/groups/${data}`);}
export async function renameGroupAction(_:GroupActionState,form:FormData):Promise<GroupActionState>{const id=String(form.get("groupId")??"");const s=await client();const{error}=await s.rpc("rename_study_group",{p_group_id:id,p_name:String(form.get("name")??"")});if(error)return failure("rename",error,"We couldn’t rename this Circle. Check the name and try again.");revalidatePath(`/groups/${id}`);return{status:"idle"};}
export async function regenerateInviteAction(_:GroupActionState,form:FormData):Promise<GroupActionState>{const id=String(form.get("groupId")??"");const s=await client();const{error}=await s.rpc("regenerate_group_invite",{p_group_id:id});if(error)return failure("regenerate_invite",error,"We couldn’t create a new invite link. Please try again.");revalidatePath(`/groups/${id}`);return{status:"idle"};}
export async function removeMemberAction(_:GroupActionState,form:FormData):Promise<GroupActionState>{const id=String(form.get("groupId")??"");const s=await client();const{error}=await s.rpc("remove_study_group_member",{p_group_id:id,p_username:String(form.get("username")??"")});if(error)return failure("remove_member",error,"We couldn’t remove that member. Refresh and try again.");revalidatePath(`/groups/${id}`);return{status:"idle"};}
export async function leaveGroupAction(_:GroupActionState,form:FormData):Promise<GroupActionState>{const s=await client();const{error}=await s.rpc("leave_study_group",{p_group_id:String(form.get("groupId")??"")});if(error)return failure("leave",error,"We couldn’t leave this Circle. Refresh and try again.");redirect("/leaderboard");}
export async function deleteGroupAction(_:GroupActionState,form:FormData):Promise<GroupActionState>{const s=await client();const{error}=await s.rpc("delete_study_group",{p_group_id:String(form.get("groupId")??"")});if(error)return failure("delete",error,"We couldn’t delete this Circle. Refresh and try again.");redirect("/leaderboard");}
