"use client";

import { useState } from "react";
import { formatDuration } from "@/lib/sessions/format";
import type { AnalyticsPoint } from "@/lib/analytics";

export type DailyChartSeries={id:string;name:string;color:string;points:AnalyticsPoint[]};
const axisHours=(seconds:number)=>seconds===0?"0h":`${(seconds/3600).toFixed(seconds<3600?1:0)}h`;

export function InteractiveDailyChart({series,ariaLabel}:{series:DailyChartSeries[];ariaLabel:string}){
 const dates=series[0]?.points.map(point=>point.date)??[];const width=Math.max(720,dates.length*18),height=300,top=18,bottom=44,left=50,right=12;
 const innerWidth=width-left-right,innerHeight=height-top-bottom;const max=Math.max(3600,...series.flatMap(item=>item.points.map(point=>point.seconds)));
 const [hovered,setHovered]=useState<string|null>(null);const[selected,setSelected]=useState<string|null>(null);const active=hovered??selected;
 const formatDate=new Intl.DateTimeFormat("en-US",{month:"long",day:"numeric",timeZone:"UTC"});const shortDate=new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",timeZone:"UTC"});
 const labelIndexes=new Set([0,Math.floor((dates.length-1)/2),dates.length-1]);
 const coords=(points:AnalyticsPoint[],index:number)=>({x:left+(points.length===1?innerWidth/2:index/(points.length-1)*innerWidth),y:top+innerHeight-(points[index]?.seconds??0)/max*innerHeight});
 const path=(points:AnalyticsPoint[])=>points.map((_,index)=>{const{x,y}=coords(points,index);return`${index?"L":"M"}${x.toFixed(1)},${y.toFixed(1)}`}).join(" ");
 const activeParts=active?.split(":");const activeSeries=series.find(item=>item.id===activeParts?.[0]);const activeIndex=activeParts?Number(activeParts[1]):-1;const activePoint=activeSeries?.points[activeIndex];const activeCoord=activeSeries&&activeIndex>=0?coords(activeSeries.points,activeIndex):null;
 return <div><div className="relative mt-5 overflow-x-auto pb-2"><div className="relative" style={{minWidth:`${width}px`}}><svg aria-label={ariaLabel} className="block w-full" role="img" viewBox={`0 0 ${width} ${height}`}>{[0,.5,1].map(ratio=><g key={ratio}><line stroke="#DDD9CF" x1={left} x2={width-right} y1={top+innerHeight*ratio} y2={top+innerHeight*ratio}/><text fill="#68736E" fontSize="11" textAnchor="end" x={left-8} y={top+innerHeight*ratio+4}>{axisHours(max*(1-ratio))}</text></g>)}{series.map(item=><g key={item.id}><path d={path(item.points)} fill="none" stroke={item.color} strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.75"/>{item.points.map((point,index)=>{const{x,y}=coords(item.points,index);const key=`${item.id}:${index}`;return <g key={point.date}><circle aria-hidden="true" cx={x} cy={y} fill={item.color} r="3"/><circle aria-label={`${item.name}, ${formatDate.format(new Date(`${point.date}T00:00:00Z`))}, ${formatDuration(point.seconds)} studied`} className="cursor-pointer focus:outline-none" cx={x} cy={y} fill="transparent" onBlur={()=>setHovered(null)} onClick={()=>setSelected(current=>current===key?null:key)} onFocus={()=>setHovered(key)} onPointerEnter={()=>setHovered(key)} onPointerLeave={()=>setHovered(null)} r="13" role="button" stroke="transparent" tabIndex={0}/></g>})}</g>)}{dates.map((date,index)=>labelIndexes.has(index)?<text fill="#68736E" fontSize="11" key={date} textAnchor={index===0?"start":index===dates.length-1?"end":"middle"} x={coords(series[0].points,index).x} y={height-10}>{shortDate.format(new Date(`${date}T00:00:00Z`))}</text>:null)}</svg>{activePoint&&activeSeries&&activeCoord&&<div className="pointer-events-none absolute z-10 w-56 rounded-field bg-ink px-4 py-3 text-paper shadow-[0_8px_24px_rgba(37,49,45,0.18)]" role="status" style={{left:`${Math.min(Math.max(activeCoord.x/width*100,16),84)}%`,top:`${Math.max(4,activeCoord.y/height*100-5)}%`,transform:"translate(-50%,-100%)"}}><p className="text-xs font-semibold text-paper">{series.length>1?`${activeSeries.name} — `:""}{formatDate.format(new Date(`${activePoint.date}T00:00:00Z`))}</p><p className="mt-1 text-sm font-semibold tabular text-white">{formatDuration(activePoint.seconds)} studied</p>{activePoint.goals.length?<ul className="mt-2 space-y-1 border-t border-white/20 pt-2">{activePoint.goals.map(goal=><li className="flex justify-between gap-3 text-xs" key={goal.name}><span className="truncate text-paper/80">{goal.name}</span><span className="shrink-0 tabular text-paper">{formatDuration(goal.seconds)}</span></li>)}</ul>:<p className="mt-2 text-xs text-paper/70">No completed study time.</p>}</div>}</div></div></div>;
}
